### PR TITLE
Create ja_jp.json

### PR DESCRIPTION
**Pull request by fixdol**
japanese translation

### CODE REVIEW

**Comment by petrolpark** [comment]
Thanks so much! I'll merge this in after 1.0 is merged into the main branch. If you're interested in the translator Badge, what's your Minecraft username?

**Comment by fixdol** [comment]
FixedDolphin927

sorry it took me so long to realise

**Comment by petrolpark** [comment]
Thanks again! Try and put the file in the right place next time, but it's no bother.

**Comment by petrolpark** [comment]
ext time

**Pull request merged**
