### PR TITLE
Fixed inconsistency of molecule density & a Basin bug

### PR DESCRIPTION
**Pull request by HenryRenYz**
Original molecule density has inconsistency through their phase, most were taken density in the liquid phase, like hydrogen, but some were taken in the gas phase, like chlorine. This makes the game display of concentration of chlorine as 0.0M. Considering that gas density can be calculated based on molar mass (ideal gas), I unified all molecule density to the density of their liquid phase, no matter how low their b.p. is.

### CODE REVIEW

**Comment by HenryRenYz** [comment]
[735b95e](https://github.com/petrolpark/Destroy/pull/309/commits/735b95e520b7c98e1a08cc896eb8561317622757): This bug is caused by a accidentally added empty fluid in class ReactionInBasinRecipe. When basin reaction results no fluid, the empty fluid will be added to the output, causing a NPE in fluid particle render of Create.

**Comment by petrolpark** [comment]
Wow! Thanks for the help.

Seeing as development is taking place on a separate branch, I may end up merging this once I've pulled that onto this repo. Maybe before. But it will probably get implemented.

Since I added it in the issues and suggestions guidelines, I've stopped reminding people about the Badge available for useful bug reports (or maybe people just don't realise [Badges](https://www.patreon.com/petrolpark/about) exist anymore, now that they've stopped receiving them for being among the first 1000 players), but here's a reminder that if you are interested in it (and for this, you shall definitely receive), do include your MC username in the bug report, or PR in this case.

**Comment by HenryRenYz** [comment]
Great! My MC username is HenryRenYz (same to github's)

**Comment by petrolpark** [comment]
I've made most all of these fixed independently now anyway, but thanks for the help. I don't remember if I added the Badge but if not you should have it now. Sorry about the delay if so.

**Pull request closed without merging**
