### PR TITLE
Fixed the Polish translation and translated some texts

### PR DESCRIPTION
**Pull request by Piecuuu**

### CODE REVIEW

**Comment by petrolpark** [comment]
Thanks for the help! I'll merge this in after 1.0 is done. What's your Minecraft username if you're interested in the [Badge](https://patreon.com/petrolpark/about)?

**Comment by Piecuuu** [comment]
> Thanks for the help! I'll merge this in after 1.0 is done. What's your Minecraft username if you're interested in the [Badge](https://patreon.com/petrolpark/about)?

My Minecraft username is Min3craftPolska. Thank you very much.

**Comment by petrolpark** [comment]
That should be added, sorry for the delay. If it doesn't appear let me know.

**Comment by Piecuuu** [comment]
> That should be added, sorry for the delay. If it doesn't appear let me know.

It does appear. Thanks.

**Pull request merged**
