### PR TITLE
Update pl_pl.json 28 Feb 2024

### PR DESCRIPTION
**Pull request by jenot1**

### CODE REVIEW

**Comment by petrolpark** [comment]
Thanks for the help! I'll merge this in after 1.0 is done. What's your Minecraft username if you're interested in the [Badge](https://patreon.com/petrolpark/about)?

**Comment by jenot1** [comment]
You're welcome!
My Minecraft nick is je_not

**Comment by petrolpark** [comment]
Should be added, let me know if not.

**Comment by jenot1** [comment]
I got it, thanks

**Pull request merged**
